spring:
  database:
    driverClassName: org.postgresql.Driver
  datasource:
    username: 'postgres'
    password: '123456'
    url: "jdbc:postgresql://localhost:5432/eagle_eye_local"
    platform: 'postgres'
    testWhileIdle: 'true'
    validationQuery: 'SELECT 1'
  jpa:
    show-sql: 'true'
    #database: POSTGRESQL
    hibernate:
        ddl-auto: 'update'
    properties:
        hibernate:
          dialect: 'org.hibernate.dialect.PostgreSQLDialect'
tracer:
  property: '"I AM THE DEFAULT"'

example:
  property: "I AM IN THE DEFAULT 2"
